# Generated by Django 5.0.6 on 2025-11-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUG', 'Bug ou problème'), ('IDEA', 'Idée d’amélioration'), ('COMMENT', 'Commentaire général')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RESOLVED', 'Résolu')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
