# Generated by Django 5.0.6 on 2025-11-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(default='Bienvenue sur CineStream', max_length=255)),
                ('top10_text', models.CharField(blank=True, default='Top 10 Afrique', max_length=255)),
                ('banner_images', models.JSONField(blank=True, default=list)),
                ('ads_images', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
