# Generated by Django 5.0.6 on 2025-11-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='ads_images',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='banner_images',
        ),
        migrations.CreateModel(
            name='AdsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/ads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_images', to='homepage.homepagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/banners/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='homepage.homepagecontent')),
            ],
        ),
    ]
