# Generated by Django 5.0.6 on 2025-11-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_homepagecontent_ads_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='carouselimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='adsimage',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='homepage',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='ads_images',
            field=models.ManyToManyField(blank=True, to='homepage.adsimage'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_images',
            field=models.ManyToManyField(blank=True, to='homepage.carouselimage'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='homepage/carousels/'),
        ),
    ]
