# Generated by Django 5.0.6 on 2025-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_uploaded_at_adsimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsimage',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
