# Generated by Django 5.0.6 on 2025-11-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Drame', 'Drame'), ('Comédie', 'Comédie'), ('Aventure', 'Aventure'), ('Romance', 'Romance'), ('Science-Fiction', 'Science-Fiction'), ('Horreur', 'Horreur'), ('Animation', 'Animation')], default='Action', max_length=50),
        ),
    ]
