# Generated by Django 5.0.6 on 2025-11-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='trailer_url',
            new_name='trailer_link',
        ),
    ]
