# Generated by Django 5.0.6 on 2025-11-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_trailer_url_movie_trailer_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/posters/'),
        ),
    ]
