# Generated by Django 5.0.6 on 2025-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_movie_price_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
