# Generated by Django 5.0.6 on 2025-11-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('DELIVERED', 'Livré')], default='PENDING', max_length=10),
        ),
    ]
