# Generated by Django 5.0.6 on 2025-11-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CineStream', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('orange_money_number', models.CharField(blank=True, max_length=50)),
                ('orange_money_name', models.CharField(blank=True, max_length=100)),
                ('mtn_money_number', models.CharField(blank=True, max_length=50)),
                ('mtn_money_name', models.CharField(blank=True, max_length=100)),
                ('telegram_message_default', models.TextField(default='Merci pour votre commande ! Notre équipe vous contactera sous peu.')),
                ('homepage_about', models.TextField(blank=True, default='')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
